In [1]:
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
type(iris)

sklearn.utils._bunch.Bunch

In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
x = iris.data

In [6]:
# x

In [7]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
# we want one-hot encoding
# class 0 --> [1,0,0]
# class 1 --> [0,1,0]
# class 2 --> [0,0,1]

In [9]:
from keras.utils import to_categorical

In [10]:
y = to_categorical(y)

In [11]:
y.shape

(150, 3)

In [13]:
# y

In [14]:
# train-test split
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [16]:
# scale and standardize the data

from sklearn.preprocessing import MinMaxScaler

In [17]:
np.array([5, 10, 15, 20]) / 20

array([0.25, 0.5 , 0.75, 1.  ])

In [18]:
scaler_object = MinMaxScaler()

In [19]:
scaler_object.fit(X_train)

MinMaxScaler()

In [20]:
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

In [22]:
#scaled_X_train

In [23]:
# build networ kwith keras

from keras.models import Sequential
from keras.layers import Dense

In [24]:
# 1-> create model
model = Sequential()

# 2-> add layers to model
model.add(Dense(8, input_dim=4, activation = "relu"))
model.add(Dense(8, input_dim=4, activation = "relu"))
model.add(Dense(3, activation = "softmax")) # we get the probability of belonging to certain class

model.compile(loss = "categorical_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.fit(scaled_X_train, y_train, epochs = 150, verbose = 2)

Epoch 1/150
4/4 - 1s - loss: 1.1202 - accuracy: 0.3100 - 966ms/epoch - 241ms/step
Epoch 2/150
4/4 - 0s - loss: 1.1159 - accuracy: 0.3100 - 12ms/epoch - 3ms/step
Epoch 3/150
4/4 - 0s - loss: 1.1122 - accuracy: 0.3100 - 12ms/epoch - 3ms/step
Epoch 4/150
4/4 - 0s - loss: 1.1084 - accuracy: 0.3100 - 15ms/epoch - 4ms/step
Epoch 5/150
4/4 - 0s - loss: 1.1052 - accuracy: 0.3000 - 13ms/epoch - 3ms/step
Epoch 6/150
4/4 - 0s - loss: 1.1026 - accuracy: 0.3000 - 14ms/epoch - 3ms/step
Epoch 7/150
4/4 - 0s - loss: 1.1002 - accuracy: 0.3000 - 15ms/epoch - 4ms/step
Epoch 8/150
4/4 - 0s - loss: 1.0974 - accuracy: 0.3100 - 12ms/epoch - 3ms/step
Epoch 9/150
4/4 - 0s - loss: 1.0953 - accuracy: 0.3100 - 14ms/epoch - 3ms/step
Epoch 10/150
4/4 - 0s - loss: 1.0936 - accuracy: 0.3200 - 274ms/epoch - 68ms/step
Epoch 11/150
4/4 - 0s - loss: 1.0917 - accuracy: 0.3700 - 13ms/epoch - 3ms/step
Epoch 12/150
4/4 - 0s - loss: 1.0901 - accuracy: 0.4000 - 14ms/epoch - 3ms/step
Epoch 13/150
4/4 - 0s - loss: 1.0883 - accur

In [27]:
# predicting on new data

## PART TWO

In [29]:
# model.predict(scaled_X_test)

In [ ]:
# model.predict_classes -> ne radi mi

In [33]:
predict_x=model.predict(scaled_X_test) 
np.argmax(predict_x,axis=1)

2/2 [==============================] - 0s 5ms/step


array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [34]:
predictions = np.argmax(model.predict(scaled_X_test), axis = 1)

2/2 [==============================] - 0s 5ms/step


In [35]:
y_test.argmax(axis = 1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [36]:
predictions

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [37]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [38]:
confusion_matrix(y_test.argmax(axis = 1), predictions)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  0, 16]], dtype=int64)

In [40]:
print(classification_report(y_test.argmax(axis = 1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.93      0.97        15
           2       0.94      1.00      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [41]:
accuracy_score(y_test.argmax(axis = 1), predictions)

0.98

In [42]:
# saving the model

model.save("myfirstmodel_handson.h5")

In [43]:
from keras.models import load_model

new_model = load_model("myfirstmodel_handson.h5")